# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 00:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readinghub', '0002_auto_20190323_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
