# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readinghub', '0004_auto_20190320_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='love.jpg', upload_to='cat_images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='lion.jpg', upload_to='event_images'),
        ),
    ]
